version: "3.2"

services:
  dev:
    container_name: fs-node
    image: paritytech/ci-linux:staging
    working_dir: /var/www/fs-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/fs-node/.cargo
    volumes:
      - .:/var/www/fs-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/fs-node--dev --ws-external"
